# Generated by Django 2.2 on 2020-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_extendeduser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='is_admin_added',
            field=models.BooleanField(default=False),
        ),
    ]
